# Change default site language
defaultContentLanguage = 'vi'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = false
disableLanguages = []

#meta data
baseURL = 'https://wwdinhww.github.io/FCJ-report-HUGO-SE192671/'
languageCode = 'en-us'
title = 'AWS INTERNSHIP REPORT'
theme = 'hugo-theme-relearn'

[caches]
[caches.images]
    dir = ':cacheDir/images'

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[params]
    # Change default color scheme with a variant one. Can be 'red', 'blue', 'green'.
    themeVariant = 'workshop'
    # Disable home button on Sidebar
    disableLandingPageButton = true

[languages]
    [languages.vi]
        contentDir = 'content/vi'
        languageCode = 'vi'
        languageName = 'Vietnamese'
        title = 'AWS Báo Cáo Thực Tập'
        weight = 1

    [languages.en]
        contentDir = 'content/en'
        languageCode = 'en'
        languageName = 'English'
        title = 'AWS Intership Report'
        weight = 2