baseURL = "http://localhost:1313/"
# baseURL = "https://wwdinhww.github.io/FCJ-report-HUGO-SE192671/"
languageCode = "en-us"
title = "Internship Report"
theme = "PaperMod"

[caches]
[caches.images]
dir = ':cacheDir/images'
