baseURL = "https://wwdinhww.github.io/FCJ-report-HUGO-SE192671/"
languageCode = "en-us"
title = "AWS INTERNSHIP REPORT"
theme = 'hugo-theme-relearn'

[caches]
[caches.images]
dir = ':cacheDir/images'
